admin_history_routes:
  resource: "@ProjectBundle/Resources/config/admin/history.yml"
  prefix:   /history

admin_location_routes:
  resource: "@ProjectBundle/Resources/config/admin/location.yml"
  prefix:   /location

admin_series_routes:
  resource: "@ProjectBundle/Resources/config/admin/series.yml"
  prefix:   /series

admin_product_technique_routes:
  resource: "@ProjectBundle/Resources/config/admin/product_technique.yml"
  prefix:   /product-technique

admin_product_category_routes:
  resource: "@ProjectBundle/Resources/config/admin/product_category.yml"
  prefix:   /product-category

admin_report_routes:
  resource: "@ProjectBundle/Resources/config/admin/report.yml"
  prefix:   /report

admin_payment_gateway_routes:
  resource: "@ProjectBundle/Resources/config/admin/payment_gateway.yml"
  prefix:   /payment-gateway

admin_customer_payment_epayment_routes:
  resource: "@ProjectBundle/Resources/config/admin/customer_payment_epayment.yml"
  prefix:   /customer-payment-epayment

admin_customer_payment_bank_transfer_routes:
  resource: "@ProjectBundle/Resources/config/admin/customer_payment_bank_transfer.yml"
  prefix:   /customer-payment-bank-transfer

admin_holiday_routes:
  resource: "@ProjectBundle/Resources/config/admin/holiday.yml"
  prefix:   /holiday

admin_shipping_rate_routes:
  resource: "@ProjectBundle/Resources/config/admin/shipping_rate.yml"
  prefix:   /shipping-rate

admin_shipping_carrier_routes:
   resource: "@ProjectBundle/Resources/config/admin/shipping_carrier.yml"
   prefix:   /shipping-carrier

admin_customer_orders_routes:
  resource: "@ProjectBundle/Resources/config/admin/customer_order.yml"
  prefix:   /customer_order

bank_account_routes:
  resource: "@ProjectBundle/Resources/config/admin/bank_account.yml"
  prefix:   /bank-account

admin_page_style_guide_routes:
  resource: "@ProjectBundle/Resources/config/admin/page_style_guide.yml"
  prefix:   /style_guide

admin_page_about_us_routes:
  resource: "@ProjectBundle/Resources/config/admin/page_about_us.yml"
  prefix:   /about_us

admin_page_portfolio_routes:
  resource: "@ProjectBundle/Resources/config/admin/page_portfolio.yml"
  prefix:   /portfolio

admin_page_service_routes:
  resource: "@ProjectBundle/Resources/config/admin/page_service.yml"
  prefix:   /service

admin_page_how_to_buy_routes:
  resource: "@ProjectBundle/Resources/config/admin/page_how_to_buy.yml"
  prefix:   /how-to-buy

admin_page_shipping_delivery_routes:
  resource: "@ProjectBundle/Resources/config/admin/page_shipping_delivery.yml"
  prefix:   /shipping-delivery

admin_page_terms_conditions_routes:
  resource: "@ProjectBundle/Resources/config/admin/page_terms_conditions.yml"
  prefix:   /terms-conditions

admin_page_privacy_policy_routes:
  resource: "@ProjectBundle/Resources/config/admin/page_privacy_policy.yml"
  prefix:   /privacy-policy

admin_page_product_detail_routes:
  resource: "@ProjectBundle/Resources/config/admin/page_product_detail.yml"
  prefix:   /product_detail

admin_styling_routes:
  resource: "@ProjectBundle/Resources/config/admin/styling.yml"
  prefix:   /styling

admin_movie_routes:
  resource: "@ProjectBundle/Resources/config/admin/movie.yml"
  prefix:   /movie




blog_routes:
  resource: "@ProjectBundle/Resources/config/admin/blog.yml"
  prefix:   /health-tips

promotion_routes:
  resource: "@ProjectBundle/Resources/config/admin/promotion.yml"
  prefix:   /promotion

#discount_routes:
#  resource: "@ProjectBundle/Resources/config/admin/discount.yml"
#  prefix:   /discount


product_routes:
  resource: "@ProjectBundle/Resources/config/admin/product.yml"
  prefix:   /products

sku_routes:
  resource: "@ProjectBundle/Resources/config/admin/sku.yml"
  prefix:   /sku

member_routes:
 resource: "@ProjectBundle/Resources/config/admin/member.yml"
 prefix:   /member

contact_routes:
  resource: "@ProjectBundle/Resources/config/admin/contact.yml"
  prefix:   /contact

authentication_routes:
  resource: "@ProjectBundle/Resources/config/admin/authentication.yml"
  prefix:   /authentication

setting_routes:
  resource: "@ProjectBundle/Resources/config/admin/setting.yml"
  prefix:   /setting

user_routes:
  resource: "@ProjectBundle/Resources/config/admin/user.yml"
  prefix:   /user

banner_routes:
  resource: "@ProjectBundle/Resources/config/admin/banner.yml"
  prefix:   /banner

showroom_routes:
  resource: "@ProjectBundle/Resources/config/admin/showroom.yml"
  prefix:   /shop

our_client_routes:
  resource: "@ProjectBundle/Resources/config/admin/our_client.yml"
  prefix:   /our-client

admin_test_routes:
  resource: "@ProjectBundle/Resources/config/admin/test.yml"
  prefix:   /test

admin:
  path:     /
  defaults: { _controller: ProjectBundle:AdminMain:index }
