admin_page_privacy_policy:
  path:  /
  defaults: { _controller: ProjectBundle:AdminPagePrivacyPolicy:index }
  requirements:
    _method: get

admin_page_privacy_policy_update:
  path: /update
  defaults: {_controller: ProjectBundle:AdminPagePrivacyPolicy:update}
  requirements:
    _method: post
    id: \d+
