admin_product_technique:
  path: /
  defaults: {_controller: ProjectBundle:AdminProductTechnique:index}
  methods:  [GET]

admin_product_technique_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminProductTechnique:new}
  methods:  [GET,POST]

admin_product_technique_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminProductTechnique:edit}
  methods:  [GET,POST]
  requirements:
    id: \d+

admin_product_technique_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminProductTechnique:delete}
  methods:  [GET]
  requirements:
    id: \d+

admin_product_technique_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminProductTechnique:group_delete}
  methods:  [POST]

admin_product_technique_sort:
  path: /sort
  defaults: {_controller: ProjectBundle:AdminProductTechnique:sort}
  methods:  [GET]

admin_product_technique_sort_prosess:
  path: /sort-prosess
  defaults: {_controller: ProjectBundle:AdminProductTechnique:sort_prosess}
  methods:  [POST]
