admin_video:
  path: /
  defaults: {_controller: ProjectBundle:AdminVideo:index}
  requirements:
    _method: get

admin_video_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminVideo:new}

admin_video_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminVideo:create}
  requirements:
    _method: post

admin_video_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminVideo:edit}
  requirements:
    id: \d+

admin_video_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminVideo:update}
  requirements:
    _method: post
    id: \d+

admin_video_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminVideo:delete}
  requirements:
    _method: get

admin_video_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminVideo:group_delete}
  requirements:
    _method: post

admin_video_group_enable:
  path: /group-enable
  defaults: {_controller: ProjectBundle:AdminVideo:group_enable}
  requirements:
    _method: post

admin_video_group_disable:
  path: /group-disable
  defaults: {_controller: ProjectBundle:AdminVideo:group_disable}
  requirements:
    _method: post

admin_video_list_series_by_category:
  path: /get-series-by-category
  defaults: {_controller: ProjectBundle:AdminVideo:listSeriesOfCategory}
  requirements:
    _method: get
