<?php

namespace ProjectBundle\Repository;

/**
 * CustomerPaymentEpaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerPaymentEpaymentRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllData($arr_query_data=false){
        $qb = $this->createQueryBuilder('cpep')
            ->innerJoin('cpep.customerOrder', 'co')
            ->orderBy('cpep.createdAt', 'DESC')
            ->groupBy('cpep.id')
            ->andWhere('co.deleted != :status')
            ->setParameter('status', 1);

        // if(isset($arr_query_data['q'])){
        //     $q = $arr_query_data['q'];
        //     $qb->where($qb->expr()->orX(
        //         $qb->expr()->like('cpep.customerOrder', ':query')
        //     ))
        //     ->setParameter('query', '%'.$q.'%');
        // }
        return $qb;

    }
    // function findEpaymentByOrder($order){
    //     $qb = $this->findAllData()
    //             ->Where('cpep.customerOrder',"");
    //     return $qb;
    //
    // }
}
