<?php

namespace ProjectBundle\Repository;

/**
 * CustomerPaymentBankTransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerPaymentBankTransferRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllData($arr_query_data=false) {
        $qb = $this->createQueryBuilder('cpbt')
            ->select('cpbt')
            ->orderBy('cpbt.createdAt', 'DESC');
        if(isset($arr_query_data['q'])){
            $q = $arr_query_data['q'];
            $qb->where($qb->expr()->orX(
                $qb->expr()->like('cpbt.orderNumber', ':query')
            ))
            ->setParameter('query', '%'.$q.'%');
        }
        return $qb;
    }

    function findAllDataJoin($arr_query_data=false) {
        $qb = $this->findAllData()
                ->select('cpbt','codit')
                ->innerJoin('cpbt.customerOrder','codit')
                ->andWhere('codit.deleted != :status')
                ->setParameter('status', 1);
        return $qb;
    }

    function findCustomerPaymentBankTransferByOrder($order) {
        $qb = $this->findAllDataJoin();
                $qb->andWhere('cpbt.customerOrder = :order')
                   ->setParameter(':order', $order);
        return $qb;
    }

}
