<?php

namespace ProjectBundle\Repository;

/**
 * ProductTechNiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTechNiqueRepository extends \Doctrine\ORM\EntityRepository
{
    private $qb;

    public function findAllData()
    {
      return $this->createQueryBuilder('ptn')
                ->orderBy('ptn.position', 'ASC')
                ->addOrderBy('ptn.createdAt', 'DESC');
    }
}
