<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use Symfony\Component\Intl\Locale;

/**
 * SeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends \Doctrine\ORM\EntityRepository
{
	private $qb;

	public function findOnePublicDataJoinedProduct($id, $locale=false)
    {
		$locale = ($locale) ? $locale : Locale::getDefault();
		$this->findAllDataJoined($locale);
		$this->qb->addSelect('p', 'pt')
				->join('s.products', 'p')
				->join('s.productCategory', 'pc')
				->join('p.translations', 'pt')
				 ->andWhere("pc.id = '$id'")
				// ->andWhere("pt.locale = '$locale'")
				->addOrderBy('p.position', 'ASC')
				->addOrderBy('p.createdAt', 'DESC');

		//public product
		$this->qb->andWhere('NOW() >= p.publishDate')
		            ->andWhere($this->qb->expr()->andX(
		                $this->qb->expr()->eq('p.status', ':status')
		            ))
            		->setParameter('status', 1);


		return $this->qb;
	}
	public function findOnePublicDataJoinedProductRelated($id,$locale=false)
	{
		$locale = ($locale) ? $locale : Locale::getDefault();
		$this->findAllDataJoined($locale);
		$this->qb->addSelect('p', 'pt')
				->join('s.products', 'p')
				->join('p.translations', 'pt')
				->andWhere("pc.id <> '$id'")
				// ->andWhere("pt.locale = '$locale'")
				->addOrderBy('p.position', 'ASC')
				->addOrderBy('p.createdAt', 'DESC')
				->orderBy('RAND()');
				;

		//public product
		$this->qb->andWhere('NOW() >= p.publishDate')
					->andWhere($this->qb->expr()->andX(
						$this->qb->expr()->eq('p.status', ':status')
					))
					->setParameter('status', 1);


		return $this->qb;
	}
	public function findSeriesDataJoinedByID($id, $locale=false)
	{
		$locale = ($locale) ? $locale : Locale::getDefault();
		$this->qb = $this->createQueryBuilder('s');
		//join translation
		$this->qb->select('s', 'st', 'pc', 'pct')
			->join('s.translations', 'st')
			->leftjoin('s.productCategory', 'pc')
			->leftjoin('pc.translations', 'pct')
			->where("pc.id = '$id'")
			->orderBy('pc.position', 'ASC')
			->addOrderBy('s.position', 'ASC')
			->addOrderBy('s.createdAt', 'DESC');

		// $this->setSearchData($arr_query_data)

		return $this->qb;
	}
	public function findNewProductInSeries($arr_query_data=false, $locale=false)
	{
		$locale = ($locale) ? $locale : Locale::getDefault();

		$this->findAllData();
		$this->qb->addSelect('s', 'st', 'p', 'pt')
				->leftjoin('s.products', 'p')
				->leftjoin('p.translations', 'pt')
				 ->addOrderBy('s.position', 'ASC')
				 ->addOrderBy('p.position', 'ASC')
				->andWhere("p.isNew = 1 and p.status = 1")
				// ->groupBy("s.id,p.id")
				// ->andWhere("st.locale = '$locale'")
				// ->andWhere("pt.locale = '$locale'")
				;

		// $this->setSearchData($arr_query_data);

		return $this->qb;
	}
	public function findSeriesByID($id, $locale=false)
	{
		$locale = ($locale) ? $locale : Locale::getDefault();
		$this->qb = $this->createQueryBuilder('s');
		//join translation
		$this->qb->select('s', 'st', 'pc', 'pct')
			->join('s.translations', 'st')
			->join('s.productCategory', 'pc')
			->join('pc.translations', 'pct')
			->join('s.products', 'p')
			->where("s.id = '$id'")
			->andWhere("p.status = 1 ")
			->orderBy('pc.position', 'ASC')
			->addOrderBy('s.position', 'ASC')
			->addOrderBy('s.createdAt', 'DESC');

		// $this->setSearchData($arr_query_data)

		return $this->qb;
	}
	public function findDataByCategory($id, $locale=false)
	{
		$locale = ($locale) ? $locale : Locale::getDefault();
		$this->qb = $this->createQueryBuilder('s');
		//join translation
		$this->qb->select('s', 'st', 'pc', 'pct')
			->join('s.translations', 'st')
			->join('s.productCategory', 'pc')
			->join('pc.translations', 'pct')
			->where("pc.id = '$id'")
			->orderBy('pc.position', 'ASC')
			->addOrderBy('s.position', 'ASC')
			->addOrderBy('s.createdAt', 'DESC');

		// $this->setSearchData($arr_query_data)

		return $this->qb;
	}

	public function findAllDataJoined($arr_query_data=false, $locale=false)
    {
		$locale = ($locale) ? $locale : Locale::getDefault();
		$this->qb = $this->createQueryBuilder('s');
		//join translation
		$this->qb->select('s', 'st', 'pc', 'pct')
			->join('s.translations', 'st')
			->leftjoin('s.productCategory', 'pc')
			->leftjoin('pc.translations', 'pct')
			// ->where("st.locale = '$locale'")
			->orderBy('pc.position', 'ASC')
			->addOrderBy('s.position', 'ASC')
			->addOrderBy('s.createdAt', 'DESC');

		$this->setSearchData($arr_query_data);

		return $this->qb;
	}

	public function findAllData($arr_query_data=false, $locale=false)
    {
		$locale = ($locale) ? $locale : Locale::getDefault();

		$this->qb = $this->createQueryBuilder('s');
		//join translation
		$this->qb->select('s', 'st')
				->join('s.translations', 'st')
				->where("st.locale = '$locale'")
				->orderBy('s.position', 'ASC')
				->addOrderBy('s.createdAt', 'DESC');

		$this->setSearchData($arr_query_data);

  		return $this->qb;
    }

	protected function setSearchData($arr_query_data)
	{
  		if(isset($arr_query_data['q'])){
			//search from translation
  			$this->qb->where($this->qb->expr()->orX(
	  	      	$this->qb->expr()->like('st.title', ':query'),
				$this->qb->expr()->like('st.subTitle', ':query'),
	  			$this->qb->expr()->like('st.shortDesc', ':query')
			))
  			->setParameter('query', '%'.$arr_query_data['q'].'%');
  		}
		if (isset($arr_query_data['productCategory']) && $arr_query_data['productCategory']){
			//search from translation
			$this->qb->andWhere($this->qb->expr()->orX(
				$this->qb->expr()->eq('pc.id', ':productCategory')
			))
			->setParameter('productCategory', $arr_query_data['productCategory']);
		}
	}
}
