default_target_login:
    path:     /default_target_login
    defaults: { _controller: ProjectBundle:Main:default_target_login }
    requirements:
      _method: get

default_target_logout:
    path:     /default_target_logout
    defaults: { _controller: ProjectBundle:Main:default_target_logout }
    requirements:
      _method: get

default_target_password_resetting:
    path:     /default_target_password_resetting
    defaults: { _controller: ProjectBundle:Main:default_target_password_resetting }
    requirements:
      _method: get

product_routes:
    resource: '@ProjectBundle/Resources/config/product.yml'
    prefix:     /product

cart_routes:
    resource: '@ProjectBundle/Resources/config/cart.yml'
    prefix:     /cart

checkout_routes:
    resource: '@ProjectBundle/Resources/config/checkout.yml'
    prefix:     /checkout

member_routes:
    resource: '@ProjectBundle/Resources/config/member.yml'
    prefix:     /member


#customer_register:
#    path:     /signup
#    defaults: { _controller: ProjectBundle:Main:customer_register }

#customer_register_create:
#    path:     /signup-create
#    defaults: { _controller: ProjectBundle:Main:customer_register_create }
#    requirements:
#      _method: post

#customer_register_complete:
#    path:     /signup-complete
#    defaults: { _controller: ProjectBundle:Main:customer_register_complete }

# style:
#     path:     /style
#     defaults: { _controller: ProjectBundle:Main:style }
#
# style_detail:
#     path:     /style/{id}/{slug}
#     defaults: { _controller: ProjectBundle:Main:style_detail }
#     requirements:
#       id: \d+
#
# blog:
#     path:     /health-tip
#     defaults: { _controller: ProjectBundle:Main:blog }
#
# blog_detail:
#     path:     /health-tip/{id}/{slug}
#     defaults: { _controller: ProjectBundle:Main:blog_detail }
#     requirements:
#       id: \d+
#
# search:
#     path:     /search
#     defaults: { _controller: ProjectBundle:Main:search }
#
# search_api:
#     path:     /search-api
#     defaults: { _controller: ProjectBundle:Main:search_api }
#     requirements:
#       _method: get
#     options:
#       expose: true
#
# about_us:
#     path:     /about-us
#     defaults: { _controller: ProjectBundle:Main:about_us }
#
# service:
#     path:     /service
#     defaults: { _controller: ProjectBundle:Main:service }
#
# how_to_buy:
#     path:     /how-to-buy
#     defaults: { _controller: ProjectBundle:Main:how_to_buy }
#
# shipping_delivery:
#     path:     /shipping-delivery
#     defaults: { _controller: ProjectBundle:Main:shipping_delivery }
#
# terms_conditions:
#     path:     /terms-conditions
#     defaults: { _controller: ProjectBundle:Main:terms_conditions }
#
# privacy_policy:
#     path:     /privacy-policy
#     defaults: { _controller: ProjectBundle:Main:privacy_policy }
#
# contact:
#     path:     /contact-us
#     defaults: { _controller: ProjectBundle:Main:contact }
#
# contact_create:
#     path: /contact-create
#     defaults: { _controller: ProjectBundle:Main:contact_create }
#     requirements:
#       _method: post
#     options:
#       expose: true
#
# showroom:
#     path:     /showroom
#     defaults: { _controller: ProjectBundle:Main:showroom }
#
# promotion:
#     path:     /promotion
#     defaults: { _controller: ProjectBundle:Main:promotion }
#
# promotion_detail:
#     path:     /promotion/{id}/{slug}
#     defaults: { _controller: ProjectBundle:Main:promotion_detail }
#     requirements:
#       id: \d+
#
# portfolio:
#     path:     /portfolio
#     defaults: { _controller: ProjectBundle:Main:portfolio }
#
#test:
#    path:     /test
#    defaults: { _controller: ProjectBundle:Main:test  }

shipping_delivery:
    path:     /shipping-delivery
    defaults: { _controller: ProjectBundle:Main:shipping_delivery }

how_to_buy:
    path:     /how-to-buy
    defaults: { _controller: ProjectBundle:Main:how_to_buy }


confirm_payment:
  path: /confirm-payment
  defaults: {_controller: ProjectBundle:Main:confirm_payment}
  requirements:
    _method: get,post

search_payment_data:
  path: /search-payment-data
  defaults: {_controller: ProjectBundle:Main:search_paymentData}
  requirements:
    _method: get,post

track:
    path:     /track
    defaults: { _controller: ProjectBundle:Main:track }
    requirements:
        _method: get
    options:
        expose: true

################################## start all skin #########################################
uv_rays_and_dryness:
    path:     /skin-problems-and-cosmetics/uv-rays-and-dryness
    defaults: { _controller: ProjectBundle:Main:uv_rays_and_dryness  }

adult_acne_advice:
    path:     /skin-problems-and-cosmetics/adult-acne/skin-care-and-makeup-advice
    defaults: { _controller: ProjectBundle:Main:adult_acne_advice  }

adult_acne:
    path:     /skin-problems-and-cosmetics/adult-acne
    defaults: { _controller: ProjectBundle:Main:adult_acne  }

skin_atopic_dermatitis_wash:
    path:     /skin-problems-and-cosmetics/skin-atopic-dermatitis/atopy-wash
    defaults: { _controller: ProjectBundle:Main:skin_atopic_dermatitis_wash  }

skin_atopic_dermatitis_qa:
    path:     /skin-problems-and-cosmetics/skin-atopic-dermatitis/QA
    defaults: { _controller: ProjectBundle:Main:skin_atopic_dermatitis_qa  }

skin_atopic_dermatitis:
    path:     /skin-problems-and-cosmetics/skin-atopic-dermatitis
    defaults: { _controller: ProjectBundle:Main:skin_atopic_dermatitis  }

skin_allergy_test:
    path:     /skin-problems-and-cosmetics/skin-allergy/test
    defaults: { _controller: ProjectBundle:Main:skin_allergy_test  }

skin_allergy_qa:
    path:     /skin-problems-and-cosmetics/skin-allergy/QA
    defaults: { _controller: ProjectBundle:Main:skin_allergy_qa  }

skin_allergy:
    path:     /skin-problems-and-cosmetics/skin-allergy
    defaults: { _controller: ProjectBundle:Main:skin_allergy  }

skin_problems_and_cosmetics :
    path:     /skin-problems-and-cosmetics
    defaults: { _controller: ProjectBundle:Main:skin_problems_and_cosmetics  }

################################## end all skin #########################################
privacy_policy:
    path:     /privacy-policy
    defaults: { _controller: ProjectBundle:Main:privacy_policy  }

sitemap:
    path:     /site-map
    defaults: { _controller: ProjectBundle:Main:sitemap  }
shop:
    path:     /shop
    defaults: { _controller: ProjectBundle:Main:shop }

in_shop_counseling:
    path:     /counseling/in-shop-counseling
    defaults: { _controller: ProjectBundle:Main:in_shop_counseling }

counseling:
    path:     /counseling
    defaults: { _controller: ProjectBundle:Main:counseling }

terms_of_use:
    path:     /terms-of-use
    defaults: { _controller: ProjectBundle:Main:terms_of_use }

company_profile:
    path:     /company-profile
    defaults: { _controller: ProjectBundle:Main:company_profile }

history:
    path:     /history
    defaults: { _controller: ProjectBundle:Main:history }

about:
    path:     /about
    defaults: { _controller: ProjectBundle:Main:about }

homepage:
    path:     /
    defaults: { _controller: ProjectBundle:Main:index }

#project_homepage:
#    path:     /
#    defaults: { _controller: ProjectBundle:Default:index }
