default_target_login:
    path:     /default_target_login
    defaults: { _controller: ProjectBundle:Main:default_target_login }
    requirements:
      _method: get

default_target_logout:
    path:     /default_target_logout
    defaults: { _controller: ProjectBundle:Main:default_target_logout }
    requirements:
      _method: get

default_target_password_resetting:
    path:     /default_target_password_resetting
    defaults: { _controller: ProjectBundle:Main:default_target_password_resetting }
    requirements:
      _method: get

# product_routes:
#     resource: '@ProjectBundle/Resources/config/product.yml'
#     prefix:     /product
#
# cart_routes:
#     resource: '@ProjectBundle/Resources/config/cart.yml'
#     prefix:     /cart
#
# checkout_routes:
#     resource: '@ProjectBundle/Resources/config/checkout.yml'
#     prefix:     /checkout
#
# member_routes:
#     resource: '@ProjectBundle/Resources/config/member.yml'
#     prefix:     /member
movies:
    path:     /movies
    defaults: { _controller: ProjectBundle:Main:movies}


styling:
    path:     /styling
    defaults: { _controller: ProjectBundle:Main:styling}

# style_guide:
#     path:     /style-guide
#     defaults: { _controller: ProjectBundle:Main:style_guide}

sitemap:
    path:     /sitemap
    defaults: { _controller: ProjectBundle:Main:sitemap}

products:
    path:     /products
    defaults: { _controller: ProjectBundle:Main:products }

new_products:
    path:     /products/new-products
    defaults: { _controller: ProjectBundle:Main:new_products }

product_series:
  path: /products/{id}/{slug}
  defaults: {_controller: ProjectBundle:Main:series}
  methods:  [GET]
  requirements:
    id: \d+
  options:
    expose: true

product_series_list:
  path: /products/{id}/{category}/{series}
  defaults: {_controller: ProjectBundle:Main:product_series_list}
  methods:  [GET]
  requirements:
    id: \d+
  options:
    expose: true


contact:
    path:     /contact-us
    defaults: { _controller: ProjectBundle:Main:contact }

contact_create:
    path: /contact-create
    defaults: { _controller: ProjectBundle:Main:contact_create }
    requirements:
      _method: post
    options:
      expose: true

homepage:
    path:     /
    defaults: { _controller: ProjectBundle:Main:index }
